################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
SX_SRCS := 
LINKER_SCRIPT := 
PP_SRCS := 
CC_SRCS := 
FSY_SRCS := 
P_SRCS := 
SRC_SRCS := 
JMP_SRCS := 
C_SRCS := 
JMP_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
P_DEPS := 
C_DEPS := 
SRC_DEPS := 
PP_DEPS := 
CC_DEPS := 
SX_DEPS := 
C++_DEPS := 
OBJS := 
CXX_DEPS := 
SECONDARY_FLASH := 
ASM_DEPS := 
S_UPPER_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
mbed-os/cmsis/TARGET_CORTEX_A \
mbed-os/components/802.15.4_RF/atmel-rf-driver/source \
mbed-os/components/802.15.4_RF/mcr20a-rf-driver/source \
mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver/source \
mbed-os/components/storage/blockdevice/COMPONENT_SD \
mbed-os/components/wifi/esp8266-driver/ESP8266 \
mbed-os/components/wifi/esp8266-driver \
mbed-os/drivers/source \
mbed-os/drivers/source/usb \
mbed-os/events/source \
mbed-os/features/cellular/framework/AT \
mbed-os/features/cellular/framework/common \
mbed-os/features/cellular/framework/device \
mbed-os/features/cellular/framework/targets/GEMALTO/CINTERION \
mbed-os/features/cellular/framework/targets/GENERIC/GENERIC_AT3GPP \
mbed-os/features/cellular/framework/targets/MultiTech/DragonflyNano/PPP \
mbed-os/features/cellular/framework/targets/QUECTEL/BC95 \
mbed-os/features/cellular/framework/targets/QUECTEL/BG96 \
mbed-os/features/cellular/framework/targets/QUECTEL/EC2X \
mbed-os/features/cellular/framework/targets/QUECTEL/M26 \
mbed-os/features/cellular/framework/targets/QUECTEL/UG96 \
mbed-os/features/cellular/framework/targets/RiotMicro/AT \
mbed-os/features/cellular/framework/targets/TELIT/HE910 \
mbed-os/features/cellular/framework/targets/TELIT/ME910 \
mbed-os/features/cellular/framework/targets/UBLOX/AT \
mbed-os/features/cellular/framework/targets/UBLOX/N2XX \
mbed-os/features/cellular/framework/targets/UBLOX/PPP \
mbed-os/features/device_key/source \
mbed-os/features/frameworks/greentea-client/source \
mbed-os/features/frameworks/mbed-client-cli/source \
mbed-os/features/frameworks/mbed-client-randlib/source \
mbed-os/features/frameworks/mbed-coap/source \
mbed-os/features/frameworks/mbed-trace/source \
mbed-os/features/frameworks/nanostack-libservice/source/IPv6_fcf_lib \
mbed-os/features/frameworks/nanostack-libservice/source/libBits \
mbed-os/features/frameworks/nanostack-libservice/source/libList \
mbed-os/features/frameworks/nanostack-libservice/source/libip4string \
mbed-os/features/frameworks/nanostack-libservice/source/libip6string \
mbed-os/features/frameworks/nanostack-libservice/source/nsdynmemLIB \
mbed-os/features/frameworks/nanostack-libservice/source/nvmHelper \
mbed-os/features/frameworks/unity/source \
mbed-os/features/frameworks/utest \
mbed-os/features/frameworks/utest/source \
mbed-os/features/lorawan \
mbed-os/features/lorawan/lorastack/mac \
mbed-os/features/lorawan/lorastack/phy \
mbed-os/features/lorawan/system \
mbed-os/features/lwipstack \
mbed-os/features/lwipstack/lwip/src/api \
mbed-os/features/lwipstack/lwip/src/core/ipv4 \
mbed-os/features/lwipstack/lwip/src/core/ipv6 \
mbed-os/features/lwipstack/lwip/src/core \
mbed-os/features/lwipstack/lwip/src/netif \
mbed-os/features/lwipstack/lwip-sys/arch \
mbed-os/features/lwipstack/lwip-sys \
mbed-os/features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL \
mbed-os/features/mbedtls/mbed-crypto/src \
mbed-os/features/mbedtls/platform/src \
mbed-os/features/mbedtls/src \
mbed-os/features/mbedtls/targets \
mbed-os/features/nanostack/coap-service/source \
mbed-os/features/nanostack/mbed-mesh-api/source \
mbed-os/features/nanostack/nanostack-hal-mbed-cmsis-rtos \
mbed-os/features/nanostack/nanostack-hal-mbed-cmsis-rtos/nvm \
mbed-os/features/nanostack/nanostack-interface \
mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/Bootstraps/Generic \
mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/Fragmentation \
mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/IPHC_Decode \
mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/MAC \
mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/Mesh \
mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/ND \
mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/NVM \
mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/Thread \
mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN \
mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws \
mbed-os/features/nanostack/sal-stack-nanostack/source/BorderRouter \
mbed-os/features/nanostack/sal-stack-nanostack/source/Common_Protocols \
mbed-os/features/nanostack/sal-stack-nanostack/source/Core \
mbed-os/features/nanostack/sal-stack-nanostack/source/DHCPv6_Server \
mbed-os/features/nanostack/sal-stack-nanostack/source/DHCPv6_client \
mbed-os/features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4 \
mbed-os/features/nanostack/sal-stack-nanostack/source/MAC/ethernet \
mbed-os/features/nanostack/sal-stack-nanostack/source/MAC \
mbed-os/features/nanostack/sal-stack-nanostack/source/MAC/serial \
mbed-os/features/nanostack/sal-stack-nanostack/source/MAC/virtual_rf \
mbed-os/features/nanostack/sal-stack-nanostack/source/MLE \
mbed-os/features/nanostack/sal-stack-nanostack/source/MPL \
mbed-os/features/nanostack/sal-stack-nanostack/source/NWK_INTERFACE \
mbed-os/features/nanostack/sal-stack-nanostack/source/RPL \
mbed-os/features/nanostack/sal-stack-nanostack/source/Security/Common \
mbed-os/features/nanostack/sal-stack-nanostack/source/Security/PANA \
mbed-os/features/nanostack/sal-stack-nanostack/source/Security/TLS \
mbed-os/features/nanostack/sal-stack-nanostack/source/Security/eapol \
mbed-os/features/nanostack/sal-stack-nanostack/source/Security/kmp \
mbed-os/features/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot \
mbed-os/features/nanostack/sal-stack-nanostack/source/Security/protocols/fwh_sec_prot \
mbed-os/features/nanostack/sal-stack-nanostack/source/Security/protocols/gkh_sec_prot \
mbed-os/features/nanostack/sal-stack-nanostack/source/Security/protocols/key_sec_prot \
mbed-os/features/nanostack/sal-stack-nanostack/source/Security/protocols \
mbed-os/features/nanostack/sal-stack-nanostack/source/Security/protocols/tls_sec_prot \
mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/CCM_lib \
mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/CCM_lib/mbedOS \
mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/Neighbor_cache \
mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/SHA256_Lib \
mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/Trickle \
mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/blacklist \
mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/etx \
mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/fhss \
mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/fnv_hash \
mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/hmac \
mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/ieee_802_11 \
mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/load_balance \
mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mac_neighbor_table \
mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/services/mdns \
mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/services/poll \
mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/stack \
mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns \
mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mle_service \
mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/nd_proxy \
mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/nist_aes_kw \
mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/pan_blacklist \
mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/utils \
mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/whiteboard \
mbed-os/features/nanostack/sal-stack-nanostack/source/ipv6_stack \
mbed-os/features/nanostack/sal-stack-nanostack/source/libDHCPv6 \
mbed-os/features/nanostack/sal-stack-nanostack/source/libNET/src \
mbed-os/features/nanostack/sal-stack-nanostack-eventloop/source \
mbed-os/features/netsocket \
mbed-os/features/netsocket/cellular \
mbed-os/features/netsocket/emac-drivers/TARGET_RZ_A1_EMAC \
mbed-os/features/netsocket/ppp/polarssl \
mbed-os/features/netsocket/ppp \
mbed-os/features/netsocket/ppp/source \
mbed-os/features/nfc/acore/source \
mbed-os/features/nfc/source/controllers \
mbed-os/features/nfc/source/nfc \
mbed-os/features/nfc/source/nfc/ndef \
mbed-os/features/nfc/source/nfc/ndef/common \
mbed-os/features/nfc/stack/ndef \
mbed-os/features/nfc/stack/platform \
mbed-os/features/nfc/stack/tech/iso7816 \
mbed-os/features/nfc/stack/tech/isodep \
mbed-os/features/nfc/stack/tech/type4 \
mbed-os/features/nfc/stack/transceiver/pn512 \
mbed-os/features/nfc/stack/transceiver \
mbed-os/features/storage/blockdevice \
mbed-os/features/storage/filesystem \
mbed-os/features/storage/filesystem/fat/ChaN \
mbed-os/features/storage/filesystem/fat \
mbed-os/features/storage/filesystem/littlefs \
mbed-os/features/storage/filesystem/littlefs/littlefs \
mbed-os/features/storage/kvstore/conf \
mbed-os/features/storage/kvstore/direct_access_devicekey \
mbed-os/features/storage/kvstore/filesystemstore \
mbed-os/features/storage/kvstore/global_api \
mbed-os/features/storage/kvstore/kv_map \
mbed-os/features/storage/kvstore/securestore \
mbed-os/features/storage/kvstore/tdbstore \
mbed-os/features/storage/nvstore/source \
mbed-os/features/storage/system_storage \
mbed-os/hal \
mbed-os/hal/mpu \
mbed-os/hal/usb \
mbed-os/platform/cxxsupport \
mbed-os/platform/source \
mbed-os/platform/source/minimal-printf \
mbed-os/rtos/source \
mbed-os/rtos/source/TARGET_CORTEX/TOOLCHAIN_GCC_ARM \
mbed-os/rtos/source/TARGET_CORTEX \
mbed-os/rtos/source/TARGET_CORTEX/rtx4 \
mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Config \
mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Config/TARGET_CORTEX_A \
mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_CORTEX_A \
mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Source \
mbed-os/rtos/source/TARGET_CORTEX/rtx5/Source \
mbed-os/targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H \
mbed-os/targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device \
mbed-os/targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/TOOLCHAIN_GCC_ARM \
mbed-os/targets/TARGET_RENESAS/TARGET_RZ_A1XX \
mbed-os/targets/TARGET_RENESAS/TARGET_RZ_A1XX/common \

